import psycopg2
import os

DATABASE_URL = os.environ.get("DATABASE_URL")


def check_barusu():
    with get_connection() as conn:
        with conn.cursor() as cur:
            try:
                cur.execute("SELECT * FROM barusu;")
            except:
                print('バルス済み')
                return True
    return False


def barusu():
    # とりあえずbarusuテーブルを削除
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("DROP TABLE IF EXISTS barusu;")
        conn.commit()
    
    # すべてのテーブルを削除
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("DROP TABLE IF EXISTS images;")
        conn.commit()

        
def init_tables():
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("DROP TABLE IF EXISTS images;")
            cur.execute("DROP TABLE IF EXISTS barusu;")
            cur.execute("CREATE TABLE images(id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, file_id text, result json, ip text, user_agent json, created_at timestamp);")
            cur.execute("CREATE TABLE barusu(dummy int);")
        conn.commit()

# データベース接続
def get_connection():
    return psycopg2.connect(DATABASE_URL)

